const state={rows:[],headers:[],geo:null,layer:null,values:new Map(),unmatched:[],breaks:[]};
const $=id=>document.getElementById(id);
const palette=['#edf3ee','#cddfd2','#9fc2aa','#66967d','#315f4f','#163e32'];
const map=L.map('map',{zoomControl:true,attributionControl:true,preferCanvas:true}).setView([-27,134],4);
const lightMap=L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:20,crossOrigin:true,attribution:'&copy; OpenStreetMap contributors &copy; CARTO'}).addTo(map);
const streetMap=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,crossOrigin:true,attribution:'&copy; OpenStreetMap contributors'});
const noBasemap=L.layerGroup();
L.control.layers({'Light map':lightMap,'Standard street map':streetMap,'No basemap':noBasemap},null,{position:'topright',collapsed:false}).addTo(map);

fetch('data/australia-postal-areas.geojson').then(r=>{if(!r.ok)throw new Error('Boundary file failed to load');return r.json()}).then(g=>state.geo=g).catch(e=>{$('fileStatus').classList.remove('hidden');$('fileStatus').textContent=e.message});

const dz=$('dropzone'),fi=$('fileInput');
dz.onclick=()=>fi.click();dz.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')fi.click()};
['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));
['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));
dz.addEventListener('drop',e=>handleFile(e.dataTransfer.files[0]));fi.onchange=()=>handleFile(fi.files[0]);

function handleFile(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(ext==='csv'){Papa.parse(file,{header:true,skipEmptyLines:'greedy',complete:r=>loadRows(file.name,r.data,r.meta.fields||[]),error:e=>alert(e.message)})}else if(['xlsx','xls'].includes(ext)){const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}),detected=detectWorkbookTable(wb);if(!detected)throw new Error('No tabular rows found in the workbook.');loadRows(file.name,detected.rows,detected.headers,`Worksheet: ${detected.sheetName} · detected header row ${detected.headerRow+1}`)}catch(err){alert('Could not read workbook: '+err.message)}};reader.readAsArrayBuffer(file)}else alert('Please upload a CSV, XLSX or XLS file.')}

const headerTerms=['postcode','post code','poa','postal area','revenue','sales','value','population','person records'];
function meaningfulHeader(v){const s=String(v??'').trim();return s&&!/^__EMPTY(?:_\d+)?$/i.test(s)&&/[a-z]/i.test(s)}
function dataCell(v){if(v===null||v===undefined||String(v).trim()==='')return false;if(typeof v==='number')return true;const s=String(v).trim();return /^\d{4}(?:\s*,\s*[A-Z]{2,3})?$/.test(s)||Number.isFinite(Number(s.replace(/[$,%\s,]/g,'')))}
function detectWorkbookTable(wb){let best=null;wb.SheetNames.forEach((sheetName,sheetIndex)=>{const ws=wb.Sheets[sheetName],preview=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true,range:0,blankrows:true}).slice(0,30);preview.forEach((row,rowIndex)=>{const real=row.filter(meaningfulHeader),following=preview.slice(rowIndex+1,Math.min(preview.length,rowIndex+6)),dataRows=following.filter(r=>r.some(dataCell)).length;if(!real.length||!dataRows)return;const termHits=real.reduce((n,v)=>n+headerTerms.filter(t=>String(v).toLowerCase().includes(t)).length,0),populatedBelow=following.reduce((n,r)=>n+r.filter(v=>String(v??'').trim()!=='').length,0),score=termHits*100+dataRows*10+Math.min(populatedBelow,20)-rowIndex*.01;const candidate={ws,sheetName,sheetIndex,headerRow:rowIndex,score};if(!best||candidate.score>best.score||(candidate.score===best.score&&sheetIndex<best.sheetIndex))best=candidate})});return best?parseDetectedTable(best):null}
function parseDetectedTable(found){const matrix=XLSX.utils.sheet_to_json(found.ws,{header:1,defval:'',raw:false,range:found.headerRow,blankrows:false});if(matrix.length<2)return null;const sourceHeaders=matrix[0],data=matrix.slice(1),usedColumns=Math.max(sourceHeaders.length,...data.map(r=>r.reduce((last,v,i)=>String(v??'').trim()?i+1:last,0))),realHeaderCount=sourceHeaders.slice(0,usedColumns).filter(meaningfulHeader).length;const headers=[],seen=new Map();for(let i=0;i<usedColumns;i++){let name=meaningfulHeader(sourceHeaders[i])?String(sourceHeaders[i]).trim():'';const hasNumericData=data.some(r=>dataCell(r[i]));if(!name&&realHeaderCount===1&&hasNumericData)name='Value';if(!name)name=`Column ${XLSX.utils.encode_col(i)}`;const count=(seen.get(name)||0)+1;seen.set(name,count);headers.push(count===1?name:`${name} ${count}`)}const rows=data.filter(r=>r.some(v=>String(v??'').trim()!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));return{...found,headers,rows}}

function loadRows(name,rows,headers,detail=''){state.rows=rows;state.headers=headers;$('fileStatus').innerHTML=`<strong>${escapeHtml(name)}</strong><br>${rows.length.toLocaleString()} rows found${detail?`<br>${escapeHtml(detail)}`:''}`;$('fileStatus').classList.remove('hidden');fillSelect($('postcodeColumn'),headers);fillSelect($('valueColumn'),headers);$('postcodeColumn').value=detect(headers,['postcode','post code','postal','poa','zip']);$('valueColumn').value=detect(headers,['revenue','sales','value','population','person records','amount','customers','count','total']);if($('postcodeColumn').value===$('valueColumn').value&&headers.length>1)$('valueColumn').value=headers[1];$('mappingControls').classList.remove('hidden')}
function fillSelect(sel,headers){sel.innerHTML=headers.map(h=>`<option value="${escapeAttr(h)}">${escapeHtml(h)}</option>`).join('')}
function detect(headers,terms){return headers.find(h=>terms.some(t=>String(h).toLowerCase().replace(/[_-]/g,' ').includes(t)))||headers[0]||''}
function cleanPostcode(v){const m=String(v??'').match(/\b(\d{4})\b/);return m?m[1]:null}
function numeric(v){if(typeof v==='number')return Number.isFinite(v)?v:null;const n=Number(String(v??'').replace(/[$,%\s,]/g,''));return Number.isFinite(n)?n:null}

$('buildButton').onclick=buildMap;$('mapTitle').oninput=()=>{$('displayTitle').textContent=$('mapTitle').value||'Australian postcode heatmap'};
function buildMap(){if(!state.geo)return alert('The postcode boundary file is still loading. Please try again.');const pc=$('postcodeColumn').value,val=$('valueColumn').value,agg=$('aggregation').value;const buckets=new Map(),unmatched=[];state.rows.forEach((row,i)=>{const p=cleanPostcode(row[pc]);const n=agg==='count'?1:numeric(row[val]);if(!p||n===null){unmatched.push({...row,_reason:!p?'Invalid postcode':'Invalid value',_row:i+2});return}if(!buckets.has(p))buckets.set(p,[]);buckets.get(p).push(n)});const values=new Map();for(const[p,arr]of buckets){values.set(p,agg==='sum'?arr.reduce((a,b)=>a+b,0):agg==='avg'?arr.reduce((a,b)=>a+b,0)/arr.length:agg==='max'?Math.max(...arr):arr.length)}const validCodes=new Set(state.geo.features.map(f=>String(f.properties.POA_CODE21)));for(const[p]of [...values])if(!validCodes.has(p)){unmatched.push({[pc]:p,[val]:values.get(p),_reason:'No matching Postal Area'});values.delete(p)}state.values=values;state.unmatched=unmatched;const nums=[...values.values()].sort((a,b)=>a-b);if(!nums.length)return alert('No valid postcode/value pairs were found. Check the selected columns.');state.breaks=makeBreaks(nums,$('scaleMode').value,6);if(state.layer)map.removeLayer(state.layer);state.layer=L.geoJSON(state.geo,{renderer:L.canvas({padding:.5}),filter:f=>values.has(String(f.properties.POA_CODE21)),style:f=>{const v=values.get(String(f.properties.POA_CODE21));return{fillColor:colour(v),fillOpacity:.62,color:'#74827c',opacity:.7,weight:.5}},onEachFeature:(f,l)=>{const p=String(f.properties.POA_CODE21),v=values.get(p);l.bindTooltip(`<strong>Postcode ${p}</strong><br><span class="tooltip-value">${formatNumber(v)}</span>`,{sticky:true});l.on({mouseover:e=>e.target.setStyle({weight:1.25,color:'#4f5f58',opacity:.9,fillOpacity:.74}),mouseout:e=>state.layer.resetStyle(e.target)})}}).addTo(map);map.fitBounds(state.layer.getBounds(),{padding:[12,12]});$('emptyState').classList.add('hidden');$('exportButton').disabled=false;$('displayTitle').textContent=$('mapTitle').value||'Australian postcode heatmap';$('displaySubtitle').textContent=`${values.size.toLocaleString()} postcodes mapped`;renderLegend();renderSummary()}
function makeBreaks(nums,mode,k){const min=nums[0],max=nums[nums.length-1];if(min===max)return Array(k+1).fill(min);if(mode==='quantile')return Array.from({length:k+1},(_,i)=>nums[Math.min(nums.length-1,Math.floor(i*(nums.length-1)/k))]);if(mode==='log'){const a=Math.log1p(Math.max(0,min)),b=Math.log1p(max);return Array.from({length:k+1},(_,i)=>Math.expm1(a+(b-a)*i/k))}return Array.from({length:k+1},(_,i)=>min+(max-min)*i/k)}
function colour(v){let i=state.breaks.findIndex((b,j)=>j>0&&v<=b)-1;if(i<0)i=palette.length-1;return palette[Math.min(palette.length-1,Math.max(0,i))]}
function renderLegend(){$('legend').innerHTML=`<div class="legend-title">${escapeHtml($('valueColumn').value)}</div>`+palette.map((c,i)=>`<div class="legend-row"><span class="swatch" style="background:${c}"></span><span>${formatNumber(state.breaks[i])} – ${formatNumber(state.breaks[i+1])}</span></div>`).join('');$('legend').classList.remove('hidden')}
function renderSummary(){const vals=[...state.values.values()],total=vals.reduce((a,b)=>a+b,0);$('summary').innerHTML=`<b>${state.values.size.toLocaleString()}</b> postcodes mapped<br>${formatNumber(total)} total value<br>${state.unmatched.length.toLocaleString()} unmatched rows`;$('summary').classList.remove('hidden');$('unmatchedPanel').classList.toggle('hidden',!state.unmatched.length)}
function formatNumber(n){return new Intl.NumberFormat('en-AU',{maximumFractionDigits:1,notation:Math.abs(n)>=1e7?'compact':'standard'}).format(n)}
$('downloadUnmatched').onclick=()=>{const csv=Papa.unparse(state.unmatched);downloadBlob(new Blob([csv],{type:'text/csv'}),'unmatched-rows.csv')};
$('exportButton').onclick=()=>{leafletImage(map,(err,canvas)=>{if(err)return alert('Export failed: '+err.message);const out=document.createElement('canvas'),ctx=out.getContext('2d'),pad=34,titleH=74;out.width=canvas.width+pad*2;out.height=canvas.height+pad*2+titleH;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,out.width,out.height);ctx.fillStyle='#17211d';ctx.font='600 24px system-ui';ctx.fillText($('displayTitle').textContent,pad,pad+26);ctx.fillStyle='#68736d';ctx.font='14px system-ui';ctx.fillText($('displaySubtitle').textContent,pad,pad+51);ctx.drawImage(canvas,pad,pad+titleH);out.toBlob(b=>downloadBlob(b,'postcode-heatmap.png'))})};
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeAttr(s){return escapeHtml(s)}
