const state={rows:[],headers:[],geo:null,layer:null,values:new Map(),unmatched:[],breaks:[],importDetail:null,columnConfidenceLow:false,mapGenerated:false,validation:{invalidRows:[],unmatchedRows:[]}};
const $=id=>document.getElementById(id);
const palette=['#edf3ee','#cddfd2','#9fc2aa','#66967d','#315f4f','#163e32'];
const map=L.map('map',{zoomControl:true,attributionControl:true,preferCanvas:true}).setView([-27,134],4);
const lightMap=L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:20,crossOrigin:true,attribution:'&copy; OpenStreetMap contributors &copy; CARTO'}).addTo(map);
const streetMap=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,crossOrigin:true,attribution:'&copy; OpenStreetMap contributors'});
const noBasemap=L.layerGroup();
L.control.layers({'Light map':lightMap,'Standard street map':streetMap,'No basemap':noBasemap},null,{position:'topright',collapsed:false}).addTo(map);

fetch('data/australia-postal-areas.geojson').then(r=>{if(!r.ok)throw new Error('Boundary file failed to load');return r.json()}).then(g=>{state.geo=g;if(state.rows.length)renderValidation()}).catch(()=>{$('fileStatus').classList.remove('hidden');$('fileStatus').textContent='The postcode boundaries could not be loaded. Please refresh and try again.'});

const dz=$('dropzone'),fi=$('fileInput');
dz.onclick=()=>fi.click();dz.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')fi.click()};
['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));
['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));
dz.addEventListener('drop',e=>handleFile(e.dataTransfer.files[0]));fi.onchange=()=>handleFile(fi.files[0]);

function handleFile(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(ext==='csv'){Papa.parse(file,{header:true,skipEmptyLines:'greedy',complete:r=>{const parsed=normaliseParsedHeaders(r.data,r.meta.fields||[]);loadRows(file.name,parsed.rows,parsed.headers)},error:e=>alert(e.message)})}else if(['xlsx','xls'].includes(ext)){const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}),detected=detectWorkbookTable(wb);if(!detected)throw new Error('No tabular rows found in the workbook.');loadRows(file.name,detected.rows,detected.headers,{sheetName:detected.sheetName,headerRow:detected.headerRow+1})}catch(err){alert('Could not read workbook: '+err.message)}};reader.readAsArrayBuffer(file)}else alert('Please upload a CSV, XLSX or XLS file.')}

const headerTerms=['postcode','post code','poa','postal area','revenue','sales','value','population','person records'];
function meaningfulHeader(v){const s=String(v??'').trim();return s&&!/^__EMPTY(?:_\d+)?$/i.test(s)&&/[a-z]/i.test(s)}
function dataCell(v){if(v===null||v===undefined||String(v).trim()==='')return false;if(typeof v==='number')return true;const s=String(v).trim();return /^\d{4}(?:\s*,\s*[A-Z]{2,3})?$/.test(s)||Number.isFinite(Number(s.replace(/[$,%\s,]/g,'')))}
function detectWorkbookTable(wb){let best=null;wb.SheetNames.forEach((sheetName,sheetIndex)=>{const ws=wb.Sheets[sheetName],preview=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true,range:0,blankrows:true}).slice(0,30);preview.forEach((row,rowIndex)=>{const real=row.filter(meaningfulHeader),following=preview.slice(rowIndex+1,Math.min(preview.length,rowIndex+6)),dataRows=following.filter(r=>r.some(dataCell)).length;if(!real.length||!dataRows)return;const termHits=real.reduce((n,v)=>n+headerTerms.filter(t=>String(v).toLowerCase().includes(t)).length,0),populatedBelow=following.reduce((n,r)=>n+r.filter(v=>String(v??'').trim()!=='').length,0),score=termHits*100+dataRows*10+Math.min(populatedBelow,20)-rowIndex*.01;const candidate={ws,sheetName,sheetIndex,headerRow:rowIndex,score};if(!best||candidate.score>best.score||(candidate.score===best.score&&sheetIndex<best.sheetIndex))best=candidate})});return best?parseDetectedTable(best):null}
function parseDetectedTable(found){const matrix=XLSX.utils.sheet_to_json(found.ws,{header:1,defval:'',raw:false,range:found.headerRow,blankrows:false});if(matrix.length<2)return null;const sourceHeaders=matrix[0],data=matrix.slice(1),usedColumns=Math.max(sourceHeaders.length,...data.map(r=>r.reduce((last,v,i)=>String(v??'').trim()?i+1:last,0))),realHeaderCount=sourceHeaders.slice(0,usedColumns).filter(meaningfulHeader).length;const headers=[],seen=new Map();for(let i=0;i<usedColumns;i++){let name=meaningfulHeader(sourceHeaders[i])?String(sourceHeaders[i]).trim():'';const hasNumericData=data.some(r=>dataCell(r[i]));if(!name&&realHeaderCount===1&&hasNumericData)name='Value';if(!name)name=`Column ${XLSX.utils.encode_col(i)}`;const count=(seen.get(name)||0)+1;seen.set(name,count);headers.push(count===1?name:`${name} ${count}`)}const rows=data.filter(r=>r.some(v=>String(v??'').trim()!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));return{...found,headers,rows}}

function normaliseParsedHeaders(rows,sourceHeaders){const realCount=sourceHeaders.filter(meaningfulHeader).length,headers=[],seen=new Map();sourceHeaders.forEach((source,i)=>{let name=meaningfulHeader(source)?String(source).trim():'';if(!name&&realCount===1&&rows.some(row=>dataCell(row[source])))name='Value';if(!name)name=`Column ${String.fromCharCode(65+i)}`;const count=(seen.get(name)||0)+1;seen.set(name,count);headers.push(count===1?name:`${name} ${count}`)});return{headers,rows:rows.map(row=>Object.fromEntries(headers.map((header,i)=>[header,row[sourceHeaders[i]]??''])))}}

function loadRows(name,rows,headers,detail=null){const populatedHeaders=headers.filter(header=>rows.some(row=>!blank(row[header])));if(!populatedHeaders.length){alert('No populated columns were found in this file.');return}state.rows=rows;state.headers=populatedHeaders;state.importDetail=detail;const excelDetail=detail?`<br>Worksheet: ${escapeHtml(detail.sheetName)} · detected header row ${detail.headerRow}`:'';$('fileStatus').innerHTML=`<strong>${escapeHtml(name)}</strong><br>${rows.length.toLocaleString()} rows found${excelDetail}`;$('fileStatus').classList.remove('hidden');fillSelect($('postcodeColumn'),populatedHeaders,rows);fillSelect($('valueColumn'),populatedHeaders,rows);const suggestions=suggestColumns(rows,populatedHeaders);$('postcodeColumn').value=suggestions.postcode;$('valueColumn').value=suggestions.value;state.columnConfidenceLow=suggestions.lowConfidence;$('mappingControls').classList.remove('hidden');renderPreview();renderValidation()}
function fillSelect(sel,headers,rows){sel.innerHTML=headers.map(header=>{const sample=rows.find(row=>!blank(row[header]))?.[header],text=sample===undefined?'':String(sample).trim(),short=text.length>24?`${text.slice(0,21)}…`:text,label=short?`${header} — e.g. ${short}`:header;return`<option value="${escapeAttr(header)}">${escapeHtml(label)}</option>`}).join('')}
function normalisedHeader(header){return String(header).toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()}
function headerTermScore(header,terms){const name=normalisedHeader(header);return terms.some(term=>name===term)?90:terms.some(term=>name.includes(term))?65:0}
function suggestColumns(rows,headers){const postcodeTerms=['postcode','post code','poa','postal area','zip'],valueTerms=['revenue','sales','population','customers','customer','amount','value','persons','person records','total'];const ranked=headers.map(header=>{const cells=rows.map(row=>row[header]).filter(value=>!blank(value)),denominator=cells.length||1,postcodeRate=cells.filter(value=>cleanPostcode(value)!==null).length/denominator,numericRate=cells.filter(value=>numeric(value)!==null).length/denominator,postcodeHeader=headerTermScore(header,postcodeTerms),valueHeader=headerTermScore(header,valueTerms),name=normalisedHeader(header),idLike=/(^|\s)(id|identifier|code|postcode|post code|poa|zip|year)(\s|$)/.test(name)||/(id|identifier)$/.test(name);return{header,postcodeRate,numericRate,postcodeHeader,valueHeader,postcodeScore:postcodeHeader+postcodeRate*100,valueScore:valueHeader+numericRate*100-(idLike?120:0)}}),postcodes=[...ranked].sort((a,b)=>b.postcodeScore-a.postcodeScore),postcode=postcodes[0],valuePool=ranked.length>1?ranked.filter(item=>item.header!==postcode.header):ranked,values=[...valuePool].sort((a,b)=>b.valueScore-a.valueScore),value=values[0],postcodeMargin=postcode.postcodeScore-(postcodes[1]?.postcodeScore??0),valueMargin=value.valueScore-(values[1]?.valueScore??0),postcodeLow=postcode.postcodeScore<60||(postcode.postcodeHeader===0&&postcode.postcodeRate<.5)||(postcode.postcodeHeader===0&&postcodeMargin<15),valueLow=value.valueScore<60||(value.valueHeader===0&&value.numericRate<.6)||(value.valueHeader===0&&valueMargin<15);return{postcode:postcode.header,value:value.header,lowConfidence:postcodeLow||valueLow}}
function renderPreview(){const detail=state.importDetail,rows=state.rows.slice(0,10),headers=state.headers,confidence=state.columnConfidenceLow?'<br><span class="selection-warning">Please confirm these columns.</span>':'<br>Suggested from headings and sample values.';$('previewDetection').innerHTML=`${detail?`Excel header row: <b>${detail.headerRow}</b><br>`:''}Postcode column: <b>${escapeHtml($('postcodeColumn').value)}</b><br>Value column: <b>${escapeHtml($('valueColumn').value)}</b>${confidence}`;$('previewHead').innerHTML=`<tr>${headers.map(h=>`<th title="${escapeAttr(h)}">${escapeHtml(h)}</th>`).join('')}</tr>`;$('previewBody').innerHTML=rows.map(row=>`<tr>${headers.map(h=>`<td title="${escapeAttr(row[h]??'')}">${escapeHtml(row[h]??'')}</td>`).join('')}</tr>`).join('')}
$('postcodeColumn').onchange=()=>{renderPreview();renderValidation()};$('valueColumn').onchange=()=>{renderPreview();renderValidation()};
function blank(v){return v===null||v===undefined||String(v).trim()===''}
function cleanPostcode(v){if(blank(v))return null;const groups=String(v).trim().match(/\d+/g)||[];if(groups.length!==1)return null;const digits=groups[0];if(digits.length===4)return digits;if(digits.length===3)return digits.padStart(4,'0');return null}
function numeric(v){if(blank(v))return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).trim(),negative=false;if(/^\(.*\)$/.test(s)){negative=true;s=s.slice(1,-1)}s=s.replace(/[$,%\s,]/g,'');if(!s)return null;const n=Number(s);return Number.isFinite(n)?(negative?-Math.abs(n):n):null}

function calculateValidation(){const pc=$('postcodeColumn').value,val=$('valueColumn').value,counts=new Map(),invalidRows=[],validEntries=[];let blankPostcodes=0,invalidPostcodes=0,blankValues=0,nonNumericValues=0;state.rows.forEach((row,i)=>{const rawPostcode=row[pc],rawValue=row[val],postcodeBlank=blank(rawPostcode),valueBlank=blank(rawValue),postcode=cleanPostcode(rawPostcode),value=numeric(rawValue),reasons=[];if(postcodeBlank){blankPostcodes++;reasons.push('Blank postcode')}else if(!postcode){invalidPostcodes++;reasons.push('Invalid postcode')}if(valueBlank){blankValues++;reasons.push('Blank value')}else if(value===null){nonNumericValues++;reasons.push('Non-numeric value')}if(reasons.length){invalidRows.push({...row,Reason:reasons.join('; '),'Source row':i+2});return}counts.set(postcode,(counts.get(postcode)||0)+1);validEntries.push({row,postcode,value,sourceRow:i+2})});const unique=[...counts.keys()],validCodes=state.geo?new Set(state.geo.features.map(f=>String(f.properties.POA_CODE21))):null,unmatchedCodes=validCodes?new Set(unique.filter(code=>!validCodes.has(code))):new Set(),unmatchedRows=validCodes?validEntries.filter(entry=>unmatchedCodes.has(entry.postcode)).map(entry=>({...entry.row,Reason:'No matching ABS Postal Area','Source row':entry.sourceRow})):[],duplicateRows=[...counts.values()].reduce((total,count)=>total+Math.max(0,count-1),0),duplicatePostcodes=[...counts.values()].filter(count=>count>1).length,matchedCount=validCodes?unique.length-unmatchedCodes.size:0,matchedPercentage=validCodes&&unique.length?matchedCount/unique.length*100:null;return{totalRows:state.rows.length,validRows:validEntries.length,blankPostcodes,invalidPostcodes,blankValues,nonNumericValues,duplicateRows,duplicatePostcodes,uniquePostcodes:unique.length,unmatchedPostcodes:validCodes?unmatchedCodes.size:null,matchedPercentage,invalidRows,unmatchedRows}}
function renderValidation(){const result=calculateValidation();state.validation=result;const metrics=[['Total input rows',result.totalRows],['Valid rows',result.validRows],['Blank postcode rows',result.blankPostcodes],['Invalid postcode rows',result.invalidPostcodes],['Blank value rows',result.blankValues],['Non-numeric value rows',result.nonNumericValues],['Duplicate input rows',result.duplicateRows],['Postcodes affected by duplicates',result.duplicatePostcodes],['Unique valid postcodes',result.uniquePostcodes],['Postcodes not matched to ABS geography',result.unmatchedPostcodes===null?'Checking…':result.unmatchedPostcodes],['Matched percentage',result.matchedPercentage===null?'Checking…':`${result.matchedPercentage.toFixed(1)}%`]];$('validationMetrics').innerHTML=metrics.map(([label,value])=>`<dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd>`).join('');const warnings=[];if(result.invalidRows.length)warnings.push(`${result.invalidRows.length.toLocaleString()} row${result.invalidRows.length===1?' has':'s have'} invalid or missing input.`);if(result.duplicateRows)warnings.push(`${result.duplicateRows.toLocaleString()} duplicate input row${result.duplicateRows===1?' will':'s will'} be combined across ${result.duplicatePostcodes.toLocaleString()} postcode${result.duplicatePostcodes===1?'':'s'}.`);if(result.unmatchedPostcodes)warnings.push(`${result.unmatchedPostcodes.toLocaleString()} valid postcode${result.unmatchedPostcodes===1?' does':'s do'} not match the ABS geography.`);$('validationWarnings').innerHTML=warnings.length?warnings.map(w=>`<div class="validation-warning">${escapeHtml(w)}</div>`).join(''):'<div class="validation-ok">No validation warnings found.</div>';$('validationStatus').textContent=result.matchedPercentage===null?'Waiting for geography':`${result.matchedPercentage.toFixed(1)}% matched`;$('downloadInvalid').disabled=!result.invalidRows.length;$('downloadValidationUnmatched').disabled=!result.unmatchedRows.length}

$('buildButton').onclick=buildMap;$('mapTitle').oninput=()=>{$('displayTitle').textContent=$('mapTitle').value||'Australian postcode heatmap'};
const aggregationLabels={sum:'Sum',avg:'Average',count:'Count',min:'Minimum',max:'Maximum'};
function aggregateValues(values,method){if(method==='avg')return values.reduce((a,b)=>a+b,0)/values.length;if(method==='count')return values.length;if(method==='min')return Math.min(...values);if(method==='max')return Math.max(...values);return values.reduce((a,b)=>a+b,0)}
function buildMap(){if(!state.geo)return alert('The postcode boundaries are still loading. Please try again.');const pc=$('postcodeColumn').value,val=$('valueColumn').value,agg=$('aggregation').value,aggLabel=aggregationLabels[agg],buckets=new Map(),unmatched=[];state.rows.forEach((row,i)=>{const p=cleanPostcode(row[pc]),n=numeric(row[val]);if(!p||n===null){unmatched.push({...row,_reason:!p?'Invalid postcode':'Invalid value',_row:i+2});return}if(!buckets.has(p))buckets.set(p,[]);buckets.get(p).push(n)});const values=new Map();for(const[p,arr]of buckets)values.set(p,aggregateValues(arr,agg));const validCodes=new Set(state.geo.features.map(f=>String(f.properties.POA_CODE21)));for(const[p]of [...values])if(!validCodes.has(p)){unmatched.push({[pc]:p,[val]:values.get(p),_reason:'No matching Postal Area'});values.delete(p)}state.values=values;state.unmatched=unmatched;const nums=[...values.values()].sort((a,b)=>a-b);if(!nums.length)return alert('No valid postcode and value pairs were found. Please check the selected columns and validation summary.');state.breaks=makeBreaks(nums,$('scaleMode').value,6);if(state.layer)map.removeLayer(state.layer);state.layer=L.geoJSON(state.geo,{renderer:L.canvas({padding:.5}),filter:f=>values.has(String(f.properties.POA_CODE21)),style:f=>{const v=values.get(String(f.properties.POA_CODE21));return{fillColor:colour(v),fillOpacity:.62,color:'#74827c',opacity:.7,weight:.5}},onEachFeature:(f,l)=>{const p=String(f.properties.POA_CODE21),v=values.get(p);l.bindTooltip(`<strong>Postcode ${p}</strong><br>${escapeHtml(aggLabel)}: <span class="tooltip-value">${formatNumber(v)}</span>`,{sticky:true});l.on({mouseover:e=>e.target.setStyle({weight:1.25,color:'#4f5f58',opacity:.9,fillOpacity:.74}),mouseout:e=>state.layer.resetStyle(e.target)})}}).addTo(map);map.fitBounds(state.layer.getBounds(),{padding:[12,12]});state.mapGenerated=true;$('emptyState').classList.add('hidden');$('exportButton').disabled=false;$('displayTitle').textContent=$('mapTitle').value||'Australian postcode heatmap';$('displaySubtitle').textContent=`${values.size.toLocaleString()} postcodes mapped · ${aggLabel}`;renderLegend();renderSummary()}
$('aggregation').onchange=()=>{renderValidation();if(state.mapGenerated)buildMap()};
function makeBreaks(nums,mode,k){const min=nums[0],max=nums[nums.length-1];if(min===max)return Array(k+1).fill(min);if(mode==='quantile')return Array.from({length:k+1},(_,i)=>nums[Math.min(nums.length-1,Math.floor(i*(nums.length-1)/k))]);if(mode==='log'){const a=Math.log1p(Math.max(0,min)),b=Math.log1p(max);return Array.from({length:k+1},(_,i)=>Math.expm1(a+(b-a)*i/k))}return Array.from({length:k+1},(_,i)=>min+(max-min)*i/k)}
function colour(v){let i=state.breaks.findIndex((b,j)=>j>0&&v<=b)-1;if(i<0)i=palette.length-1;return palette[Math.min(palette.length-1,Math.max(0,i))]}
function renderLegend(){const aggLabel=aggregationLabels[$('aggregation').value];$('legend').innerHTML=`<div class="legend-title">${escapeHtml($('valueColumn').value)} · ${escapeHtml(aggLabel)}</div>`+palette.map((c,i)=>`<div class="legend-row"><span class="swatch" style="background:${c}"></span><span>${formatNumber(state.breaks[i])} – ${formatNumber(state.breaks[i+1])}</span></div>`).join('');$('legend').classList.remove('hidden')}
function renderSummary(){const vals=[...state.values.values()],total=vals.reduce((a,b)=>a+b,0),aggLabel=aggregationLabels[$('aggregation').value];$('summary').innerHTML=`<b>${state.values.size.toLocaleString()}</b> postcodes mapped<br>${escapeHtml(aggLabel)} result total: ${formatNumber(total)}<br>${state.unmatched.length.toLocaleString()} unmatched rows`;$('summary').classList.remove('hidden');$('unmatchedPanel').classList.toggle('hidden',!state.unmatched.length);renderUnmatchedPreview()}
function renderUnmatchedPreview(){const rows=state.unmatched.slice(0,10);if(!rows.length)return;const fields=[...new Set(rows.flatMap(row=>Object.keys(row)))],labels={_reason:'Reason',_row:'Source row'};$('unmatchedPreviewCount').textContent=`First ${rows.length} of ${state.unmatched.length.toLocaleString()}`;$('unmatchedHead').innerHTML=`<tr>${fields.map(field=>`<th title="${escapeAttr(labels[field]||field)}">${escapeHtml(labels[field]||field)}</th>`).join('')}</tr>`;$('unmatchedBody').innerHTML=rows.map(row=>`<tr>${fields.map(field=>`<td title="${escapeAttr(row[field]??'')}">${escapeHtml(row[field]??'')}</td>`).join('')}</tr>`).join('')}
function formatNumber(n){return new Intl.NumberFormat('en-AU',{maximumFractionDigits:1,notation:Math.abs(n)>=1e7?'compact':'standard'}).format(n)}
$('downloadUnmatched').onclick=()=>{const csv=Papa.unparse(state.unmatched);downloadBlob(new Blob([csv],{type:'text/csv'}),'unmatched-rows.csv')};
$('downloadInvalid').onclick=()=>{const csv=Papa.unparse(state.validation.invalidRows);downloadBlob(new Blob([csv],{type:'text/csv'}),'invalid-rows.csv')};
$('downloadValidationUnmatched').onclick=()=>{const csv=Papa.unparse(state.validation.unmatchedRows);downloadBlob(new Blob([csv],{type:'text/csv'}),'abs-unmatched-rows.csv')};
$('exportButton').onclick=()=>{leafletImage(map,(err,canvas)=>{if(err)return alert('Export failed: '+err.message);const out=document.createElement('canvas'),ctx=out.getContext('2d'),pad=34,titleH=74;out.width=canvas.width+pad*2;out.height=canvas.height+pad*2+titleH;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,out.width,out.height);ctx.fillStyle='#17211d';ctx.font='600 24px system-ui';ctx.fillText($('displayTitle').textContent,pad,pad+26);ctx.fillStyle='#68736d';ctx.font='14px system-ui';ctx.fillText($('displaySubtitle').textContent,pad,pad+51);ctx.drawImage(canvas,pad,pad+titleH);out.toBlob(b=>downloadBlob(b,'postcode-heatmap.png'))})};
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeAttr(s){return escapeHtml(s)}
